# This deployment is now deprecated and you should be using deploy-dataflow-template

name: Deploy job
on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      job_name:
        required: true
        type: string
      java_version:
        type: string
        default: 11
    secrets:
      GCP_PUBLISHER_SERVICE_ACCOUNT_KEY:
        required: true
      GH_PACKAGES_READ_ACCESS_TOKEN:
        required: true
      GH_DEPLOYMENT_CREATION_ACCESS_TOKEN:
        required: true
      ARTIFACTORY_PASSWORD:
        required: false

env:
  job_location: ${{ inputs.module_name }}-jobs
  global_job_name: ${{ inputs.module_name }}-jobs-${{ inputs.job_name }}
  artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java_version }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_PUBLISHER_SERVICE_ACCOUNT_KEY }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - id: get_version_env
        name: Get job version and deployment env
        run: |
          echo "version=$([ '${{ github.ref }}' == 'refs/heads/master' ] && git rev-parse --short HEAD || ./gradlew --quiet --console=plain -Prelease.quiet -Pgpr.read.user=${{ inputs.module_name }} -Pgpr.read.key=${{ secrets.GH_PACKAGES_READ_ACCESS_TOKEN }} ${{ env.job_location }}:${{ env.global_job_name }}:currentVersion | tail -n1 )" >> $GITHUB_OUTPUT
          echo "env=$([ '${{ github.ref }}' == 'refs/heads/master' ] && echo 'dev' || echo 'prod')" >> $GITHUB_OUTPUT

      - name: Publish Dataflow Template
        if: ${{ env.artifactory_password == null }}
        run: >
          ./gradlew :${{ env.job_location }}:${{ env.global_job_name }}:run
          -Pgpr.read.user=${{ inputs.module_name }}
          -Pgpr.read.key=${{ secrets.GH_PACKAGES_READ_ACCESS_TOKEN }}
          --args="--runner=DataflowRunner --project=attraqt-xo --region=europe-west1 --stagingLocation=gs://xo-dataflow/staging --tempLocation=gs://xo-dataflow/tmp --templateLocation=gs://xo-dataflow/templates/${{ env.global_job_name }}/${{ steps.get_version_env.outputs.version }}"

      - name: Publish Dataflow Template
        if: ${{ env.artifactory_password != null }}
        run: >
          ./gradlew :${{ env.job_location }}:${{ env.global_job_name }}:run
          -Pgpr.read.user=${{ inputs.module_name }}
          -Pgpr.read.key=${{ secrets.GH_PACKAGES_READ_ACCESS_TOKEN }}
          -Partifactory.user=travis-npm
          -Partifactory.password=${{ secrets.ARTIFACTORY_PASSWORD }}
          --args="--runner=DataflowRunner --project=attraqt-xo --region=europe-west1 --stagingLocation=gs://xo-dataflow/staging --tempLocation=gs://xo-dataflow/tmp --templateLocation=gs://xo-dataflow/templates/${{ env.global_job_name }}/${{ steps.get_version_env.outputs.version }}"

      - name: Deploy
        id: deploy
        uses: Attraqt/github_actions/.github/actions/deploy@main
        with:
          repo: xo-terragrunt-${{ steps.get_version_env.outputs.env }}
          ref: master
          environment: ${{ steps.get_version_env.outputs.env }}
          token: ${{ secrets.GH_DEPLOYMENT_CREATION_ACCESS_TOKEN }}
          task: ${{ env.global_job_name }}:${{ steps.get_version_env.outputs.version }}
          required_contexts: <<EMPTY>>
