name: Deploy gRPC service
on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      service_name:
        required: true
        type: string
      deploy_on_gateway:
        required: false
        type: boolean
        default: false
    secrets:
      GCP_PUBLISHER_SERVICE_ACCOUNT_KEY:
        required: true
      GH_PACKAGES_READ_ACCESS_TOKEN:
        required: true
      GH_DEPLOYMENT_CREATION_ACCESS_TOKEN:
        required: true
      ARTIFACTORY_PASSWORD:
        required: false

env:
  final_name: ${{ inputs.module_name }}-${{ inputs.service_name }}
  artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  publish_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch tag history
        run: git fetch --prune --unshallow
        if: github.ref == 'refs/heads/master'

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_PUBLISHER_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true


      - name: Configure docker authentication
        run: gcloud auth configure-docker

      - name: Get docker tag and deployment env
        id: get_context
        run: |
          VERSION=$([ '${{ github.ref }}' == 'refs/heads/master' ] && git rev-parse --short HEAD || ./gradlew --quiet --console=plain -Prelease.quiet ${{ env.final_name }}:currentVersion | tail -n1 )
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=image_name::eu.gcr.io/attraqt-xo/${{ env.final_name }}:$VERSION"
          echo "::set-output name=gateway_image_name::eu.gcr.io/attraqt-xo/items-grpc-gateway:$VERSION"
          echo "::set-output name=env::$([ '${{ github.ref }}' == 'refs/heads/master' ] && echo 'dev' || echo 'prod')"

      - name: Build Docker image
        run: ./gradlew -Pgpr.read.user=${{ inputs.module_name }} -Pgpr.read.key=${{ secrets.GH_PACKAGES_READ_ACCESS_TOKEN }} ${{ env.final_name }}:bootBuildImage --imageName=${{ steps.get_context.outputs.image_name }}
        if: ${{ env.artifactory_password == null }}

      - name: Build Docker image
        run: > 
          ./gradlew 
          -Pgpr.read.user=${{ inputs.module_name }} 
          -Pgpr.read.key=${{ secrets.GH_PACKAGES_READ_ACCESS_TOKEN }}
          -Partifactory.user=travis
          -Partifactory.password=${{ secrets.ARTIFACTORY_PASSWORD }}
          ${{ env.final_name }}:bootBuildImage 
          --imageName=${{ steps.get_context.outputs.image_name }}
        if: ${{ env.artifactory_password != null }}

      - name: Build gateway Docker image
        run: ./gradlew -Pgpr.read.user=${{ inputs.module_name }} -Pgpr.read.key=${{ secrets.GH_PACKAGES_READ_ACCESS_TOKEN }} ${{ env.final_name }}:bootBuildImage --imageName=${{ steps.get_context.outputs.gateway_image_name }}
        if: inputs.deploy_on_gateway

      - name: Push Docker image
        run: docker push ${{ steps.get_context.outputs.image_name }}

      - name: Push gateway Docker image
        run: docker push ${{ steps.get_context.outputs.gateway_image_name }}
        if: inputs.deploy_on_gateway

      - name: Deploy
        uses: Attraqt/github_actions/.github/actions/deploy@main
        with:
          repo: xo-terragrunt-${{ steps.get_context.outputs.env }}
          ref: master
          environment: ${{ steps.get_context.outputs.env }}
          token: ${{ secrets.GH_DEPLOYMENT_CREATION_ACCESS_TOKEN }}
          task: ${{ env.final_name }}:${{ steps.get_context.outputs.version }}
          required_contexts: <<EMPTY>>
