name: Publish grpc
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      ARTIFACTORY_USER:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true
      GCP_PUBLISHER_SERVICE_ACCOUNT_KEY:
        required: true
      GH_PACKAGES_ATTRAQT_READ_ACCESS_TOKEN:
        required: true
      GH_DEPLOYMENT_CREATION_ACCESS_TOKEN:
        required: true

env:
  final_name: search-${{ inputs.service_name }}

jobs:
  publish_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch tag history
        run: git fetch --prune --unshallow
        if: contains(fromJson('["refs/heads/develop", "refs/heads/master"]'), github.ref)

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_PUBLISHER_SERVICE_ACCOUNT_KEY }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure docker authentication
        run: gcloud auth configure-docker --quiet

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # If the commit is tagged, use it. Else, use the commit hash as tag
      # If develop branch, use 'dev' terragrunt project. Else, use 'prod' project
      # If develop branch, use 'dev' environment. If master branch and untagged, use 'staging' environment. Else, use 'prod'
      - name: Get deployment tag, project and environment
        id: tag_env
        run: |
          echo "tag=$([[ '${{ github.ref }}' == refs/heads/* ]] && git rev-parse --short HEAD || ./gradlew --quiet --console=plain -Prelease.quiet ${{ env.final_name }}:currentVersion )" >> $GITHUB_OUTPUT
          echo "project=$([ '${{ github.ref }}' == 'refs/heads/develop' ] && echo 'dev' || echo 'prod')" >> $GITHUB_OUTPUT
          echo "env=$(if [ '${{ github.ref }}' == 'refs/heads/develop' ]; then echo 'dev'; elif [ '${{ github.ref }}' == 'refs/heads/master' ]; then echo 'staging'; else echo 'prod'; fi)" >> $GITHUB_OUTPUT

      - name: Build & Publish Docker image
        run: |
          ./gradlew \
            -Pgpr.read.user=search \
            -Pgpr.read.key=${{ secrets.GH_PACKAGES_ATTRAQT_READ_ACCESS_TOKEN }} \
            -Partifactory.user=${{ secrets.ARTIFACTORY_USER }} \
            -Partifactory.password=${{ secrets.ARTIFACTORY_PASSWORD }} \
            -Pdocker.tag=${{ steps.tag_env.outputs.tag }} \
            :${{ env.final_name }}:dockerPushImage --console=plain

      - name: Deploy
        uses: Attraqt/github_actions/.github/actions/deploy@main
        with:
          required_contexts: <<EMPTY>>
          repo: xo-terragrunt-${{ steps.tag_env.outputs.project }}
          ref: master
          environment: ${{ steps.tag_env.outputs.env }}
          token: ${{ secrets.GH_DEPLOYMENT_CREATION_ACCESS_TOKEN }}
          task: ${{ env.final_name }}:${{ steps.tag_env.outputs.tag }}
